#TODO(FrankPermenter): Remove this file
#cc_library(
#    name = "api",
#    hdrs = [ "conex.h" ],
#    visibility = ["//visibility:public"],
#)
#
#cc_library(name="libconex", 
#           deps = ["//conex:conex_lib", "api"],
#           alwayslink = 1, 
#           copts = ["-fPIC"],
#           srcs = ["conex.cc"], 
#           hdrs = ["conex.h"])
#
#cc_binary(name="libconex.so", 
#          linkopts = ["-static-libstdc++"],
#          deps=[":libconex"], 
#          linkshared=1,
#          linkstatic=1,
#          )
